### ISSUE TITLE
osmium_toogr2 core dump on empty PBF files

### ISSUE THREAD

**Issue by wosch** [osmcode/osm-gis-export#9] opened 2018-05-21 11:53 UTC
I run osmium_toogr2  on an empty PBF file and it crashed with a core dump:

$ touch /tmp/a.pbf
./osmium_toogr2 /tmp/a.pbf 
Pass 1...
terminate called after throwing an instance of 'osmium::pbf_error'
  what():  PBF error: blob contains no data
Aborted (core dumped)

I'm not sure if what the standard says about empty PBF files. osmosis can handle them well, osmconvert complains.

**Comment by joto** [comment] 2018-05-21 14:30
An empty file isn't valid PBF I would argue. Do you have a use case where it would make sense to handle this in some way? How?

**Comment by joto** [comment] 2021-01-17 15:54
Crash is duplicate of #6. Having an error in this case is okay.

**Closed as completed by joto** 2021-01-17 15:54 UTC
